services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDotEnv: true
      - key: SECRET_KEY
        fromDotEnv: true
